working_directory = "/Users/mikhail/"

[font]
size = 12.0

[font.bold]
family = "SauceCodePro Nerd Font"
style = "Bold"

[font.bold_italic]
family = "SauceCodePro Nerd Font"
style = "Bold Italic"

[font.italic]
family = "SauceCodePro Nerd Font"
style = "Italic"

[font.normal]
family = "SauceCodePro Nerd Font" 
style = "Regular"

[window]
dimensions = { columns = 120, lines = 50 }
position = {x = 580, y = 140}
padding = {x = 10, y = 5}
decorations = "Buttonless"
option_as_alt = "Both"

[mouse]
bindings = [{ mouse = "Middle", action = "Paste" }]
hide_when_typing = true
